name: Build KPIs

on:
  push:
    paths:
      - "setlist/**"
      - "etl/**"
      - "data/**"
      - ".github/workflows/etl.yml"
  schedule:
    - cron: "30 18 * * 0"   # Sundays 12:30 PM America/Chicago = 18:30 UTC (adjust if DST differs)
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r etl/requirements.txt

      - name: Run ETL
        run: python etl/build_kpis.py

      - name: Commit & push KPI artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(etl): refresh KPI CSVs"
          file_pattern: data/*.csv

